### PR TITLE
Class refactor

### PR DESCRIPTION
**Pull request by juba**
This PR is a refactoring of the JS htmlwidget declaration. By using a class and creating object it seems that the code is a bit more organised and readable.

I also moved the helper function `css_safe` to a separate `utils.js` file.

@timelyportfolio when you have time, could you let me know what you think, if it seems useful or maybe if you thought of other and more meaningful refactoring patterns ? Thanks !

### CODE REVIEW

**Comment by juba** [comment]
Ok, I should have given a bit more explanations on this I think.

To deal with asynchronous dynamic notebook import I used the "builder" pattern described here : 

https://stackoverflow.com/a/43433773

As a result, the body of `renderValue` is now quite small : it justs creates a new RObservable class instance and stores it as an `el` property, or just retrieve this property if it exists. Then the instance params are set, and it is the class params setter function which in turns run the methods that add observers and update variables.

I hope it is sufficiently clear, don't hesitate to tell me if this not the case.

**Comment by timelyportfolio** [comment]
I think it definitely looks cleaner.  I am familiar with the pattern but in not in the `async` context, so I can't comment on the advantages and disadvantages versus a bare `object` or functional approach.

The first thing I noticed is with `observers`.  Since these are set up and defined with every update in `set`, we are back in a situation where these get set up repeatedly.  It seems with initial testing that observable does overwrite though rather than duplicate, so maybe it is ok but the purist in me would like to see these only set up once.  However, only once means a user would not be able to add an `observer` post-render unless we check `_scope` which might be worse or look for error with `variable`.  I guess we can optimize later.  More importantly, we lose the Shiny input communication with `observers` with the refactor and `fulfilled` only gets called at initialization.  Here is some example code.

```
library(shiny)
library(robservable)
library(scales)

ui <- robservableOutput("robs")

server <- function(input, output, session) {
  output$robs <- renderRobservable({
    invalidateLater(1000, session)
    robservable(
      "@d3/bar-chart",
      cell= "chart",
      observers = "color",
      input = list(color = scales::brewer_pal(type="div")(9)[floor(runif(1,1,9))])
    )
  })
  
  observeEvent(input$robs_color, {
    print(input$robs_color)
  })
}

shinyApp(ui, server)
```

I feel fairly confident that the `observer` does not cause this issue.  The code works correctly if we move `this.add_variable_observers()` into the `constructor` which I think makes more sense for now especially if we add `proxy` methods.  With proxy methods, the likelihood of duplicating `observers` should go down, and we can add a check for duplicate to avoid any issues.

**Comment by juba** [comment]
First, sorry for not taking into account the issue of duplicated observers you mentioned and fixed in #5, and thanks for taking the time to check again on this and providing a sample app.

I added some commits to the PR which, I think, could solve this problem for now : 

- Each time an observer is added, the created variable is pushed to a new `params.observers_variables` object.
- When an `robservable` widget is updated, the previous `observers_variables` is retrieved from `el.params`, and we can compare it with `params.observers`. New observers are created, and old ones are deleted.

To simplify the code I removed the ability to give a named list to the `observers` R argument, as it provides little interest... Sorry for changing my mind about this, we may reintroduce it later if we find it is really useful ?

I think with this rewrite your example is working, as well as the following one which tries to illustrate observers creation and deletion : 

```r
library(shiny)
library(robservable)
library(leaflet)

ui <- fluidPage(

    # Application title
    titlePanel("Test robservable"),

    sidebarLayout(
        sidebarPanel(
            selectInput("input_widget", "Input widget", choices = c("usaMap1", "worldMap1")),
            robservableOutput("map_input", height = 550)
        ),
        mainPanel(
            leafletOutput("map", width = 600, height = 600)
        )
    )
)

server <- function(input, output) {

    output$map_input <- renderRobservable({
        robservable(
            "@jashkenas/inputs",
            cell = c("worldMapCoordinates", "viewof worldMap1", "usaMapCoordinates", "viewof usaMap1"),
            hide = c("worldMapCoordinates", "usaMapCoordinates"),
            observers = input$input_widget
        )
    })

    point <- reactive({
        switch(input$input_widget,
               worldMap1 = cbind(
                input$map_input_worldMap1[1],
                input$map_input_worldMap1[2]),
               usaMap1 = cbind(
                   input$map_input_usaMap1[1],
                   input$map_input_usaMap1[2])
        )
    })

    output$map <- renderLeaflet({
        leaflet(options = leafletOptions(minZoom = 10, maxZoom = 10)) %>%
            addTiles() %>%
            addMarkers(data = point())
    })
}

shinyApp(ui = ui, server = server)
``` 

The real question for me here is : how much does this refactoring impacts your idea of proxy implementation ? Will it still be possible with this rewrite, and does it imply more work for you if you already started to implement it ?

**Comment by timelyportfolio** [comment]
@juba I like the changes, but I am concerned that users might have an unpleasant surprise if `observers` are deleted implicitly when they do not include in the list.  My expectation would be that once I add an `observer` that it will remain active until I explicitly request its removal.  In my mind, this is where proxy actions would offer a better more direct way to add/delete/change `observers`.

Should we move the `observers` and `proxy` discussion to a separate branch and their respective issues?  Hopefully, I will have some time over the weekend to sketch out a proxy, but Father's day is Sunday, so not sure.

**Comment by juba** [comment]
Is it ok for you if I merge this PR after removing the code that removes observers ? Then we could continue this discussion in the Shiny proxy issue ? Or do you prefer the actual code to implement the proxy feature ?

**Comment by timelyportfolio** [comment]
@juba merging this with a working observer implementation (your choice) sounds great.  Working on `proxy` separately would be my preference.

**Comment by timelyportfolio** [comment]
thanks so much @juba.

**Comment by juba** [comment]
Thanks to you for your feedback ! And happy Father's day :-)

**Pull request merged**
